# Generated by Django 2.2.18 on 2021-02-14 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('chosen_equal', models.CharField(choices=[('S', 'Same'), ('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('left_card', models.CharField(blank=True, max_length=3)),
                ('right_card', models.CharField(blank=True, max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
